### ISSUE TITLE
😄 Thanks!

### ISSUE THREAD

**Issue by marijn** [jeffkreeftmeijer/enough.css#1]
Hey Jeff, no issue, just a thank you note. I find myself grabbing for `enough.css` very often. It is a great way to get started with, well, enough :-) Thanks!

**Comment by jeffkreeftmeijer** [comment]
Ha, thanks @marijn. This is surely my best first issue ever. Please let me know when you use it in another project, so we can start keeping a list. :)

**Comment by marijn** [comment]
Still awesome. Project is not public so can't share it. Must have used it at least in 10 different products over the past year or so. My go to starting point.
